title: "Brandon Picq"
email: "brandon.picq@gmail.com"
description: "Portfolio professionnel de Brandon PICQ — Présentation, projets et contact"
baseurl: "/PortefolioJekyll"
url: "https://brandonpicq.github.io"

theme: minima
plugins:
  - jekyll-seo-tag

collections:
  projects:
    output: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      css: "/assets/project.css"
